# Sample encrypted secrets (to be encrypted with sops)
api_key: "sample-api-key-replace-me"
db_password: "sample-db-password-replace-me"
jwt_secret: "sample-jwt-secret-replace-me"

# Environment-specific configs
environments:
  development:
    debug: true
    log_level: "debug"
  staging:
    debug: false
    log_level: "info"
  production:
    debug: false
    log_level: "error"