# SOPS configuration for secrets management
creation_rules:
  - path_regex: \.yaml$
    encrypted_regex: ^(password|secret|token|key)$
    pgp: >-
      AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,
      BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

# Age recipients (alternative to PGP)
creation_rules:
  - path_regex: \.env$
    age: >-
      age1abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz