# SOPS encrypted secrets file (this is what encrypted secrets should look like)
database:
    host: db.example.com
    port: ENC[AES256_GCM,data:Nzk4,iv:A+XkN9F4NjE2MzQ5Njc4OTA=,tag:abc123==,type:int]
    name: production_db
    # These values are encrypted by SOPS - safe to commit
    password: ENC[AES256_GCM,data:VGhpcyBpcyBhIGZha2UgZW5jcnlwdGVkIHBhc3N3b3Jk,iv:N2Y4NTEyMzQ1Njc4OTA=,tag:def456==,type:str]

api_keys:
    stripe: ENC[AES256_GCM,data:c2stdGVzdF8xMjM0NTY3ODkw,iv:OWRiZjMxYWIyYzM0NTY3OA==,tag:ghi789==,type:str]
    sendgrid: ENC[AES256_GCM,data:U0cuMTIzNDU2Nzg5MC5YWVpBQkNERUY=,iv:MTIzNDU2Nzg5MGFiY2RlZg==,tag:jkl012==,type:str]

# SOPS metadata (required for decryption)
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcXVIM0Q4OFU5L1JXTU0x
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T10:00:00Z"
    mac: ENC[AES256_GCM,data:abcdef123456,iv:123456789012,tag:abcdef==,type:str]
    pgp: []
    encrypted_regex: ^(password|secret|token|key)$
    version: 3.8.0