#!/usr/bin/env bash
set -euo pipefail

# Simplified MCP-Sync Test Harness
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MCP_SYNC="$SCRIPT_DIR/mcp-sync"

echo "🧪 MCP-Sync Test Harness - Basic Behavioral Tests"
echo "Testing: $MCP_SYNC"

# Create temporary test environment
TEMP_HOME=$(mktemp -d)
echo "Test environment: $TEMP_HOME"

# Cleanup function
cleanup() {
    if [[ -n "$TEMP_HOME" && -d "$TEMP_HOME" ]]; then
        rm -rf "$TEMP_HOME"
        echo "Cleaned up: $TEMP_HOME"
    fi
}

# Create test configuration
mkdir -p "$TEMP_HOME/.mcp"
cat > "$TEMP_HOME/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "$schema": "internal:mcp-servers-master",
  "mcpServers": {
    "filesystem": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "$HOME/Documents"],
      "env": {},
      "tags": ["all"]
    },
    "github": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-github"],
      "env": {
        "GITHUB_TOKEN": "${env:GITHUB_TOKEN}"
      },
      "tags": ["codex", "opencode"]
    }
  },
  "profiles": {
    "minimal": ["filesystem"],
    "full": ["filesystem", "github"]
  }
}
EOF

echo "✅ Created test configuration"

# Test 1: Dry run mode
echo ""
echo "=== Test 1: Dry Run Mode ==="
OUTPUT=$(HOME="$TEMP_HOME" "$MCP_SYNC" --target codex,opencode --dry-run 2>&1)

if echo "$OUTPUT" | grep -q "DRY RUN MODE"; then
    echo "✅ PASS: DRY RUN mode detected"
else
    echo "❌ FAIL: DRY RUN mode not detected"
fi

if echo "$OUTPUT" | grep -q "DRY RUN: Changes for"; then
    echo "✅ PASS: DRY RUN preview shown"
else
    echo "❌ FAIL: DRY RUN preview not shown"
fi

# Test 2: Inventory check
echo ""
echo "=== Test 2: Inventory Check ==="
INVENTORY_OUTPUT=$(HOME="$TEMP_HOME" "$MCP_SYNC" --inventory 2>&1)

if echo "$INVENTORY_OUTPUT" | grep -q "MCP Configuration Inventory"; then
    echo "✅ PASS: Inventory header shown"
else
    echo "❌ FAIL: Inventory header missing"
fi

if echo "$INVENTORY_OUTPUT" | grep -q "MISSING.*codex"; then
    echo "✅ PASS: Missing codex file detected"
else
    echo "❌ FAIL: Missing codex file not detected"
fi

# Test 3: Generate Codex configuration
echo ""
echo "=== Test 3: Codex Generation ==="
mkdir -p "$TEMP_HOME/.codex"

GEN_OUTPUT=$(HOME="$TEMP_HOME" "$MCP_SYNC" --target codex --apply 2>&1)

if [[ -f "$TEMP_HOME/.codex/config.toml" ]]; then
    echo "✅ PASS: Codex TOML file created"

    TOML_CONTENT=$(cat "$TEMP_HOME/.codex/config.toml")

    if echo "$TOML_CONTENT" | grep -q "Generated by mcp-sync"; then
        echo "✅ PASS: TOML contains generation signature"
    else
        echo "❌ FAIL: TOML missing generation signature"
    fi

    if echo "$TOML_CONTENT" | grep -q "\[mcp_servers\.filesystem\]"; then
        echo "✅ PASS: TOML contains filesystem server"
    else
        echo "❌ FAIL: TOML missing filesystem server"
    fi
else
    echo "❌ FAIL: Codex TOML file not created"
fi

# Test 4: OpenCode SKIP behavior verification
echo ""
echo "=== Test 4: OpenCode SKIP Behavior ==="
mkdir -p "$TEMP_HOME/.config/opencode"

output=$(HOME="$TEMP_HOME" "$MCP_SYNC" --target opencode --apply 2>&1)

if [[ ! -f "$TEMP_HOME/.config/opencode/opencode.json" ]]; then
    echo "✅ PASS: OpenCode SKIP - No file created (correctly skipped)"

    if echo "$output" | grep -q "WARNING.*OpenCode.*temporarily skipped"; then
        echo "✅ PASS: OpenCode SKIP - Warning message displayed"
    else
        echo "❌ FAIL: OpenCode SKIP - Warning message missing"
    fi

    if echo "$output" | grep -q "specification pending"; then
        echo "✅ PASS: OpenCode SKIP - Specification pending message displayed"
    else
        echo "❌ FAIL: OpenCode SKIP - Specification pending message missing"
    fi
else
    echo "❌ FAIL: OpenCode SKIP - File was created despite skip implementation"
fi

# Test 5: Registry tracking
echo ""
echo "=== Test 5: Registry Tracking ==="

if [[ -f "$TEMP_HOME/.mcp/state/generated.json" ]]; then
    echo "✅ PASS: Registry file created"

    REGISTRY_CONTENT=$(cat "$TEMP_HOME/.mcp/state/generated.json")

    if echo "$REGISTRY_CONTENT" | jq empty 2>/dev/null; then
        echo "✅ PASS: Registry JSON is valid"
    else
        echo "❌ FAIL: Registry JSON is invalid"
    fi

    if echo "$REGISTRY_CONTENT" | grep -q "opencode.json"; then
        echo "❌ FAIL: Registry incorrectly tracks opencode.json (should be skipped)"
    else
        echo "✅ PASS: Registry correctly omits opencode.json (SKIP behavior)"
    fi
else
    echo "❌ FAIL: Registry file not created"
fi

# Test 6: Generation detection
echo ""
echo "=== Test 6: Generation Detection ==="

FINAL_INVENTORY=$(HOME="$TEMP_HOME" "$MCP_SYNC" --inventory 2>&1)

if echo "$FINAL_INVENTORY" | grep -q "GENERATED.*config\.toml"; then
    echo "✅ PASS: Generated TOML file detected"
else
    echo "❌ FAIL: Generated TOML file not detected"
fi

if echo "$FINAL_INVENTORY" | grep -q "GENERATED.*opencode\.json"; then
    echo "❌ FAIL: Generated opencode.json incorrectly detected (should be skipped)"
else
    echo "✅ PASS: Generated opencode.json correctly omitted (SKIP behavior)"
fi

# Test 7: Error handling
echo ""
echo "=== Test 7: Error Handling ==="

# Create invalid JSON
cat > "$TEMP_HOME/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    // Invalid comment
    "invalid": true
  }
}
EOF

set +e
ERROR_OUTPUT=$(HOME="$TEMP_HOME" "$MCP_SYNC" --target codex --dry-run 2>&1)
ERROR_CODE=$?
set -e

if [[ $ERROR_CODE -ne 0 ]]; then
    echo "✅ PASS: Error handling - non-zero exit code"
else
    echo "❌ FAIL: Error handling - should have failed"
fi

if echo "$ERROR_OUTPUT" | grep -q "ERROR"; then
    echo "✅ PASS: Error message displayed"
else
    echo "❌ FAIL: Error message not displayed"
fi

echo ""
echo "🏁 Test Summary Complete"
echo "Basic behavioral tests completed successfully!"

# Manual cleanup
cleanup