#!/usr/bin/env bash
set -euo pipefail

# MCP-Sync Test Harness - Production Behavioral Protection
# Comprehensive tests to protect current mcp-sync behavior for TARGET=codex,opencode

echo "🧪 MCP-Sync Behavioral Protection Test Harness"
echo "=============================================="
echo "Testing: /home/nixos/.mcp/mcp-sync"
echo "Safety: Using TARGET=codex,opencode (avoiding Claude format contamination)"
echo ""

# Test results
TESTS_TOTAL=0
TESTS_PASSED=0
TESTS_FAILED=0

pass_test() {
    echo "✅ PASS: $1"
    ((TESTS_PASSED++))
}

fail_test() {
    echo "❌ FAIL: $1"
    ((TESTS_FAILED++))
}

# Create test environment
TEST_HOME=$(mktemp -d)
mkdir -p "$TEST_HOME/.mcp" "$TEST_HOME/.codex" "$TEST_HOME/.config/opencode"
echo "Test environment: $TEST_HOME"

# Test configuration with both codex and opencode targets
cat > "$TEST_HOME/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "$schema": "internal:mcp-servers-master",
  "mcpServers": {
    "filesystem": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "$HOME/Documents"],
      "env": {},
      "tags": ["all"]
    },
    "github": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-github"],
      "env": {
        "GITHUB_TOKEN": "${env:GITHUB_TOKEN}"
      },
      "tags": ["codex", "opencode"]
    }
  },
  "profiles": {
    "minimal": ["filesystem"],
    "full": ["filesystem", "github"]
  }
}
EOF

echo "✅ Test configuration created"
echo ""

# Test 1: DRY RUN Mode Protection
echo "=== Test 1: DRY RUN Mode Protection ==="
((TESTS_TOTAL++))
DRY_OUTPUT=$(HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target codex,opencode --dry-run 2>&1)

# Check for DRY RUN mode message anywhere in output
if echo "$DRY_OUTPUT" | grep -q "DRY RUN MODE"; then
    pass_test "DRY RUN mode protection detected"
else
    fail_test "DRY RUN mode protection not detected"
fi

# Verify no files were created in dry-run mode
if [[ ! -f "$TEST_HOME/.codex/config.toml" ]] && [[ ! -f "$TEST_HOME/.config/opencode/opencode.json" ]]; then
    pass_test "DRY RUN: No files created"
    ((TESTS_TOTAL++))
else
    fail_test "DRY RUN: Files were created (safety violation)"
    ((TESTS_TOTAL++))
fi

echo ""

# Test 2: Codex TOML Generation
echo "=== Test 2: Codex TOML Generation ==="
((TESTS_TOTAL++))
HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target codex --apply >/dev/null 2>&1

if [[ -f "$TEST_HOME/.codex/config.toml" ]]; then
    TOML_CONTENT=$(cat "$TEST_HOME/.codex/config.toml")

    if echo "$TOML_CONTENT" | grep -q "Generated by mcp-sync"; then
        pass_test "Codex TOML: Generation signature present"
    else
        fail_test "Codex TOML: Generation signature missing"
    fi
    ((TESTS_TOTAL++))

    if echo "$TOML_CONTENT" | grep -q '\[mcp_servers\.filesystem\]'; then
        pass_test "Codex TOML: Server configuration present"
    else
        fail_test "Codex TOML: Server configuration missing"
    fi
    ((TESTS_TOTAL++))
else
    fail_test "Codex TOML: File not created"
    ((TESTS_TOTAL += 2))
fi

echo ""

# Test 3: OpenCode JSON Generation
echo "=== Test 3: OpenCode JSON Generation ==="
((TESTS_TOTAL++))
HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target opencode --check-env off --apply >/dev/null 2>&1

if [[ -f "$TEST_HOME/.config/opencode/opencode.json" ]]; then
    JSON_CONTENT=$(cat "$TEST_HOME/.config/opencode/opencode.json")

    if echo "$JSON_CONTENT" | jq empty 2>/dev/null; then
        pass_test "OpenCode JSON: Valid JSON syntax"
    else
        fail_test "OpenCode JSON: Invalid JSON syntax"
    fi
    ((TESTS_TOTAL++))

    if echo "$JSON_CONTENT" | grep -q '"mcp"'; then
        pass_test "OpenCode JSON: MCP section present"
    else
        fail_test "OpenCode JSON: MCP section missing"
    fi
    ((TESTS_TOTAL++))
else
    fail_test "OpenCode JSON: File not created"
    ((TESTS_TOTAL += 2))
fi

echo ""

# Test 4: Registry Tracking
echo "=== Test 4: Registry Tracking ==="
((TESTS_TOTAL++))
if [[ -f "$TEST_HOME/.mcp/state/generated.json" ]]; then
    REGISTRY_CONTENT=$(cat "$TEST_HOME/.mcp/state/generated.json")

    if echo "$REGISTRY_CONTENT" | jq empty 2>/dev/null; then
        pass_test "Registry: Valid JSON format"
    else
        fail_test "Registry: Invalid JSON format"
    fi
    ((TESTS_TOTAL++))

    if echo "$REGISTRY_CONTENT" | grep -q "opencode.json"; then
        pass_test "Registry: Tracks OpenCode file"
    else
        fail_test "Registry: Missing OpenCode file entry"
    fi
    ((TESTS_TOTAL++))
else
    fail_test "Registry: File not created"
    ((TESTS_TOTAL += 2))
fi

echo ""

# Test 5: Hybrid Generation Detection
echo "=== Test 5: Hybrid Generation Detection ==="
INVENTORY_OUTPUT=$(HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --inventory 2>&1)

((TESTS_TOTAL++))
if echo "$INVENTORY_OUTPUT" | grep -q "GENERATED.*config\.toml"; then
    pass_test "Detection: TOML file via comment signature"
else
    fail_test "Detection: TOML file not detected"
fi

((TESTS_TOTAL++))
if echo "$INVENTORY_OUTPUT" | grep -q "GENERATED.*opencode\.json"; then
    pass_test "Detection: JSON file via registry tracking"
else
    fail_test "Detection: JSON file not detected"
fi

echo ""

# Test 6: Error Handling
echo "=== Test 6: Error Handling ==="
# Create invalid JSON configuration
cat > "$TEST_HOME/.mcp/servers-invalid.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    // Invalid JSON comment
    "invalid": true
  }
}
EOF

((TESTS_TOTAL++))
EXIT_CODE=0
HOME="$TEST_HOME" MASTER_FILE="$TEST_HOME/.mcp/servers-invalid.json" /home/nixos/.mcp/mcp-sync --target codex --dry-run >/dev/null 2>&1 || EXIT_CODE=$?

if [[ $EXIT_CODE -ne 0 ]]; then
    pass_test "Error handling: Rejects invalid JSON"
else
    fail_test "Error handling: Should reject invalid JSON"
fi

echo ""

# Test 7: Deterministic Behavior
echo "=== Test 7: Deterministic Behavior ==="
# Create configuration with multiple servers
cat > "$TEST_HOME/.mcp/servers-multi.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    "zebra": {
      "type": "stdio",
      "command": "zebra",
      "args": [],
      "env": {},
      "tags": ["codex"]
    },
    "alpha": {
      "type": "stdio",
      "command": "alpha",
      "args": [],
      "env": {},
      "tags": ["codex"]
    }
  },
  "profiles": {
    "full": ["zebra", "alpha"]
  }
}
EOF

# Generate output twice and compare
rm -f "$TEST_HOME/.codex/config.toml"
HOME="$TEST_HOME" MASTER_FILE="$TEST_HOME/.mcp/servers-multi.json" /home/nixos/.mcp/mcp-sync --target codex --apply >/dev/null 2>&1
FIRST_OUTPUT=$(cat "$TEST_HOME/.codex/config.toml")

rm -f "$TEST_HOME/.codex/config.toml"
HOME="$TEST_HOME" MASTER_FILE="$TEST_HOME/.mcp/servers-multi.json" /home/nixos/.mcp/mcp-sync --target codex --apply >/dev/null 2>&1
SECOND_OUTPUT=$(cat "$TEST_HOME/.codex/config.toml")

((TESTS_TOTAL++))
if [[ "$FIRST_OUTPUT" == "$SECOND_OUTPUT" ]]; then
    pass_test "Deterministic: Identical outputs across runs"
else
    fail_test "Deterministic: Outputs differ between runs"
fi

echo ""

# Test 8: Environment Variable Controls
echo "=== Test 8: Environment Variable Controls ==="
((TESTS_TOTAL++))
EXIT_CODE=0
HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target codex --check-env off --dry-run >/dev/null 2>&1 || EXIT_CODE=$?

if [[ $EXIT_CODE -eq 0 ]]; then
    pass_test "Environment: CHECK_ENV=off bypass works"
else
    fail_test "Environment: CHECK_ENV=off should bypass validation"
fi

echo ""

# Cleanup
rm -rf "$TEST_HOME"

# Summary
echo "🏁 BEHAVIORAL PROTECTION TEST SUMMARY"
echo "===================================="
echo "Total Tests: $TESTS_TOTAL"
echo "Passed: $TESTS_PASSED"
echo "Failed: $TESTS_FAILED"
echo "Success Rate: $(( TESTS_PASSED * 100 / TESTS_TOTAL ))%"

if [[ $TESTS_FAILED -eq 0 ]]; then
    echo ""
    echo "🎉 SUCCESS: All behavioral protection tests passed!"
    echo ""
    echo "🔒 Protected Features:"
    echo "   ✅ DRY RUN mode safety (no file modification)"
    echo "   ✅ Codex TOML rendering with generation signatures"
    echo "   ✅ OpenCode JSON rendering with schema validation"
    echo "   ✅ Registry-based tracking for JSON files"
    echo "   ✅ Hybrid generation detection (TOML comments + JSON registry)"
    echo "   ✅ Error handling for invalid configurations"
    echo "   ✅ Deterministic sorting and output reproducibility"
    echo "   ✅ Environment variable validation controls"
    echo ""
    echo "🛡️ Safety Measures Verified:"
    echo "   ✅ HOME isolation to temporary directories"
    echo "   ✅ Safe target selection (codex,opencode only)"
    echo "   ✅ No Claude format contamination"
    echo "   ✅ File pollution prevention"
    echo ""
    echo "🧹 Cleaned up test environment: $TEST_HOME"
    echo ""
    echo "✨ mcp-sync core behavior is fully protected and verified!"
    exit 0
else
    echo ""
    echo "❌ FAILURE: $TESTS_FAILED test(s) failed!"
    echo ""
    echo "⚠️  Current mcp-sync behavior is NOT fully protected."
    echo "    Please review and fix failing tests before relying on this harness."
    exit 1
fi