#!/usr/bin/env bash
set -euo pipefail

echo "🧪 MCP-Sync Minimal Test"
echo "========================"

# Create test environment
TEST_HOME=$(mktemp -d)
mkdir -p "$TEST_HOME/.mcp" "$TEST_HOME/.codex" "$TEST_HOME/.config/opencode"

echo "Test environment: $TEST_HOME"

# Simple test configuration
cat > "$TEST_HOME/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    "test": {
      "type": "stdio",
      "command": "echo",
      "args": [],
      "env": {},
      "tags": ["codex", "opencode"]
    }
  },
  "profiles": {
    "full": ["test"]
  }
}
EOF

echo "✅ Created test configuration"

echo ""
echo "=== Test 1: DRY RUN ==="
if HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target codex --dry-run 2>&1 | grep -q "DRY RUN MODE"; then
    echo "✅ DRY RUN mode works"
else
    echo "❌ DRY RUN mode failed"
fi

echo ""
echo "=== Test 2: Codex Generation ==="
HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target codex --apply >/dev/null 2>&1

if [[ -f "$TEST_HOME/.codex/config.toml" ]]; then
    echo "✅ Codex TOML created"
    if grep -q "Generated by mcp-sync" "$TEST_HOME/.codex/config.toml"; then
        echo "✅ Generation signature present"
    else
        echo "❌ Generation signature missing"
    fi
else
    echo "❌ Codex TOML not created"
fi

echo ""
echo "=== Test 3: OpenCode SKIP Behavior ==="
output=$(HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target opencode --apply 2>&1)

if [[ ! -f "$TEST_HOME/.config/opencode/opencode.json" ]]; then
    echo "✅ OpenCode SKIP: No file created (correctly skipped)"
    if echo "$output" | grep -q "WARNING.*OpenCode.*temporarily skipped"; then
        echo "✅ OpenCode SKIP: Warning message displayed"
    else
        echo "❌ OpenCode SKIP: Warning message missing"
    fi
else
    echo "❌ OpenCode SKIP: File was created despite skip"
fi

echo ""
echo "=== Test 4: Registry ==="
if [[ -f "$TEST_HOME/.mcp/state/generated.json" ]]; then
    echo "✅ Registry created"
else
    echo "❌ Registry not created"
fi

echo ""
echo "=== Test 5: Detection ==="
if HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --inventory 2>&1 | grep -q "GENERATED"; then
    echo "✅ Generation detection works"
else
    echo "❌ Generation detection failed"
fi

# Cleanup
rm -rf "$TEST_HOME"
echo ""
echo "🧹 Cleanup complete"
echo "🎉 Basic tests completed!"