#!/usr/bin/env bash
set -euo pipefail

# MCP-Sync Test Harness - Final Version
# Minimal behavioral protection tests for current mcp-sync implementation

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MCP_SYNC="$SCRIPT_DIR/mcp-sync"

echo "🧪 MCP-Sync Test Harness - Behavioral Protection Tests"
echo "Testing: $MCP_SYNC"
echo "Safety: Using TARGET=codex,opencode (avoiding Claude format contamination)"
echo ""

# Test counter
TESTS=0
PASSED=0
FAILED=0

run_test() {
    local test_name="$1"
    local test_func="$2"

    echo "=== $test_name ==="
    ((TESTS++))

    if $test_func; then
        echo "✅ PASS: $test_name"
        ((PASSED++))
    else
        echo "❌ FAIL: $test_name"
        ((FAILED++))
    fi
    echo ""
}

# Test 1: DRY RUN mode verification
test_dry_run_mode() {
    local temp_home=$(mktemp -d)

    # Setup
    mkdir -p "$temp_home/.mcp"
    cat > "$temp_home/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    "test": {
      "type": "stdio",
      "command": "echo",
      "args": [],
      "env": {},
      "tags": ["codex"]
    }
  },
  "profiles": {
    "full": ["test"]
  }
}
EOF

    # Execute
    local output
    output=$(HOME="$temp_home" "$MCP_SYNC" --target codex --dry-run 2>&1)

    # Cleanup
    rm -rf "$temp_home"

    # Assertions
    echo "$output" | grep -q "DRY RUN MODE" && \
    echo "$output" | grep -q "DRY RUN: Changes for codex"
}

# Test 2: Codex TOML rendering
test_codex_toml_rendering() {
    local temp_home=$(mktemp -d)

    # Setup
    mkdir -p "$temp_home/.mcp" "$temp_home/.codex"
    cat > "$temp_home/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    "filesystem": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem"],
      "env": {},
      "tags": ["codex"]
    }
  },
  "profiles": {
    "full": ["filesystem"]
  }
}
EOF

    # Execute
    HOME="$temp_home" "$MCP_SYNC" --target codex --apply >/dev/null 2>&1

    # Check result
    local result=true
    if [[ ! -f "$temp_home/.codex/config.toml" ]]; then
        result=false
    else
        local content=$(cat "$temp_home/.codex/config.toml")
        if ! echo "$content" | grep -q "Generated by mcp-sync"; then
            result=false
        fi
        if ! echo "$content" | grep -q '\[mcp_servers\.filesystem\]'; then
            result=false
        fi
        if ! echo "$content" | grep -q 'command = "npx"'; then
            result=false
        fi
    fi

    # Cleanup
    rm -rf "$temp_home"

    $result
}

# Test 3: OpenCode SKIP behavior verification
test_opencode_skip_behavior() {
    local temp_home=$(mktemp -d)

    # Setup
    mkdir -p "$temp_home/.mcp" "$temp_home/.config/opencode"
    cat > "$temp_home/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    "github": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-github"],
      "env": {
        "GITHUB_TOKEN": "${env:GITHUB_TOKEN}"
      },
      "tags": ["opencode"]
    }
  },
  "profiles": {
    "full": ["github"]
  }
}
EOF

    # Execute and capture stderr (disable env checking for this test)
    local output
    output=$(HOME="$temp_home" "$MCP_SYNC" --target opencode --check-env off --apply 2>&1)

    # Check result: OpenCode should be skipped with warning
    local result=true

    # Verify no OpenCode file was created (SKIP behavior)
    if [[ -f "$temp_home/.config/opencode/opencode.json" ]]; then
        result=false
    fi

    # Verify SKIP warning message is displayed
    if ! echo "$output" | grep -q "WARNING.*OpenCode.*temporarily skipped"; then
        result=false
    fi

    # Verify specification pending message
    if ! echo "$output" | grep -q "specification pending"; then
        result=false
    fi

    # Cleanup
    rm -rf "$temp_home"

    $result
}

# Test 4: Registry tracking for JSON files
test_registry_tracking() {
    local temp_home=$(mktemp -d)

    # Setup
    mkdir -p "$temp_home/.mcp" "$temp_home/.config/opencode"
    cat > "$temp_home/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    "test": {
      "type": "stdio",
      "command": "echo",
      "args": [],
      "env": {},
      "tags": ["opencode"]
    }
  },
  "profiles": {
    "full": ["test"]
  }
}
EOF

    # Execute
    HOME="$temp_home" "$MCP_SYNC" --target opencode --apply >/dev/null 2>&1

    # Check registry
    local result=true
    if [[ ! -f "$temp_home/.mcp/state/generated.json" ]]; then
        result=false
    else
        local registry=$(cat "$temp_home/.mcp/state/generated.json")
        if ! echo "$registry" | jq empty 2>/dev/null; then
            result=false
        fi
        if ! echo "$registry" | grep -q "opencode.json"; then
            result=false
        fi
        if ! echo "$registry" | grep -q "sha256"; then
            result=false
        fi
    fi

    # Cleanup
    rm -rf "$temp_home"

    $result
}

# Test 5: Generation detection
test_generation_detection() {
    local temp_home=$(mktemp -d)

    # Setup
    mkdir -p "$temp_home/.mcp" "$temp_home/.codex"
    cat > "$temp_home/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    "test": {
      "type": "stdio",
      "command": "echo",
      "args": [],
      "env": {},
      "tags": ["codex"]
    }
  },
  "profiles": {
    "full": ["test"]
  }
}
EOF

    # Generate file
    HOME="$temp_home" "$MCP_SYNC" --target codex --apply >/dev/null 2>&1

    # Check inventory detection
    local output
    output=$(HOME="$temp_home" "$MCP_SYNC" --inventory 2>&1)

    # Cleanup
    rm -rf "$temp_home"

    echo "$output" | grep -q "GENERATED.*config\.toml"
}

# Test 6: Error handling
test_error_handling() {
    local temp_home=$(mktemp -d)

    # Setup invalid JSON
    mkdir -p "$temp_home/.mcp"
    cat > "$temp_home/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    // Invalid comment
    "test": {}
  }
}
EOF

    # Execute and check error
    local exit_code=0
    HOME="$temp_home" "$MCP_SYNC" --target codex --dry-run >/dev/null 2>&1 || exit_code=$?

    # Cleanup
    rm -rf "$temp_home"

    [[ $exit_code -ne 0 ]]
}

# Test 7: Deterministic sorting
test_deterministic_sorting() {
    local temp_home=$(mktemp -d)

    # Setup with multiple servers in non-alphabetical order
    mkdir -p "$temp_home/.mcp" "$temp_home/.codex"
    cat > "$temp_home/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    "zebra": {
      "type": "stdio",
      "command": "zebra",
      "args": [],
      "env": {},
      "tags": ["codex"]
    },
    "alpha": {
      "type": "stdio",
      "command": "alpha",
      "args": [],
      "env": {},
      "tags": ["codex"]
    },
    "beta": {
      "type": "stdio",
      "command": "beta",
      "args": [],
      "env": {},
      "tags": ["codex"]
    }
  },
  "profiles": {
    "full": ["zebra", "alpha", "beta"]
  }
}
EOF

    # Generate twice and compare
    HOME="$temp_home" "$MCP_SYNC" --target codex --apply >/dev/null 2>&1
    local first_output=$(cat "$temp_home/.codex/config.toml")

    rm "$temp_home/.codex/config.toml"

    HOME="$temp_home" "$MCP_SYNC" --target codex --apply >/dev/null 2>&1
    local second_output=$(cat "$temp_home/.codex/config.toml")

    # Cleanup
    rm -rf "$temp_home"

    [[ "$first_output" == "$second_output" ]]
}

# Run all tests
run_test "Test 1: DRY RUN Mode" test_dry_run_mode
run_test "Test 2: Codex TOML Rendering" test_codex_toml_rendering
run_test "Test 3: OpenCode SKIP Behavior" test_opencode_skip_behavior
run_test "Test 4: Registry Tracking" test_registry_tracking
run_test "Test 5: Generation Detection" test_generation_detection
run_test "Test 6: Error Handling" test_error_handling
run_test "Test 7: Deterministic Sorting" test_deterministic_sorting

# Summary
echo "🏁 Test Summary"
echo "==============="
echo "Total: $TESTS"
echo "Passed: $PASSED"
echo "Failed: $FAILED"

if [[ $FAILED -eq 0 ]]; then
    echo ""
    echo "🎉 All tests passed! mcp-sync behavior is protected."
    exit 0
else
    echo ""
    echo "💥 Some tests failed!"
    exit 1
fi