#!/usr/bin/env bash
set -euo pipefail

# MCP-Sync Test Harness v2.0 - Production Perfect Protection
# Comprehensive tests for mcp-sync v2.0 including OpenCode SKIP and new safety features

echo "🧪 MCP-Sync Behavioral Protection Test Harness"
echo "=============================================="
echo "Testing: /home/nixos/.mcp/mcp-sync"
echo "Safety: Testing v2.0 features including OpenCode SKIP and enhanced security"
echo ""

# Test results
TESTS_TOTAL=0
TESTS_PASSED=0
TESTS_FAILED=0

pass_test() {
    echo "✅ PASS: $1"
    ((TESTS_PASSED++))
}

fail_test() {
    echo "❌ FAIL: $1"
    ((TESTS_FAILED++))
}

# Create test environment
TEST_HOME=$(mktemp -d)
mkdir -p "$TEST_HOME/.mcp" "$TEST_HOME/.codex" "$TEST_HOME/.config/opencode"
echo "Test environment: $TEST_HOME"

# Test configuration with both codex and opencode targets
cat > "$TEST_HOME/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "$schema": "internal:mcp-servers-master",
  "mcpServers": {
    "filesystem": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "$HOME/Documents"],
      "env": {},
      "tags": ["all"]
    },
    "simple": {
      "type": "stdio",
      "command": "echo",
      "args": ["test"],
      "env": {},
      "tags": ["codex", "opencode"]
    }
  },
  "profiles": {
    "minimal": ["filesystem"],
    "full": ["filesystem", "simple"]
  }
}
EOF

echo "✅ Test configuration created"
echo ""

# Test 1: DRY RUN Mode Protection
echo "=== Test 1: DRY RUN Mode Protection ==="
((TESTS_TOTAL++))
# Use codex only since opencode is skipped
# Run dry-run test
DRY_OUTPUT_FILE=$(mktemp)
if HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target codex --dry-run --check-env off > "$DRY_OUTPUT_FILE" 2>&1; then
    DRY_OUTPUT=$(cat "$DRY_OUTPUT_FILE")
    DRY_SUCCESS=true
else
    DRY_OUTPUT=$(cat "$DRY_OUTPUT_FILE")
    DRY_SUCCESS=false
fi
rm -f "$DRY_OUTPUT_FILE"

# Check for DRY RUN mode message anywhere in output
if echo "$DRY_OUTPUT" | grep -q "DRY RUN MODE"; then
    pass_test "DRY RUN mode protection detected"
else
    fail_test "DRY RUN mode protection not detected"
fi

# Verify no files were created in dry-run mode (only check codex since opencode is skipped)
if [[ ! -f "$TEST_HOME/.codex/config.toml" ]]; then
    pass_test "DRY RUN: No files created"
    ((TESTS_TOTAL++))
else
    fail_test "DRY RUN: Files were created (safety violation)"
    ((TESTS_TOTAL++))
fi

echo ""

# Test 2: Codex TOML Generation
echo "=== Test 2: Codex TOML Generation ==="
((TESTS_TOTAL++))
HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target codex --apply --check-env off >/dev/null 2>&1

if [[ -f "$TEST_HOME/.codex/config.toml" ]]; then
    TOML_CONTENT=$(cat "$TEST_HOME/.codex/config.toml")

    if echo "$TOML_CONTENT" | grep -q "Generated by mcp-sync"; then
        pass_test "Codex TOML: Generation signature present"
    else
        fail_test "Codex TOML: Generation signature missing"
    fi
    ((TESTS_TOTAL++))

    if echo "$TOML_CONTENT" | grep -q '\[mcp_servers\.filesystem\]'; then
        pass_test "Codex TOML: Server configuration present"
    else
        fail_test "Codex TOML: Server configuration missing"
    fi
    ((TESTS_TOTAL++))
else
    fail_test "Codex TOML: File not created"
    ((TESTS_TOTAL += 2))
fi

echo ""

# Test 3: OpenCode SKIP Warning Verification
echo "=== Test 3: OpenCode SKIP Warning Verification ==="
((TESTS_TOTAL++))
OPENCODE_OUTPUT=$(HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target opencode --apply --check-env off 2>&1)

# Check for OpenCode skip warning
if echo "$OPENCODE_OUTPUT" | grep -q "WARNING: OpenCode target is temporarily skipped"; then
    pass_test "OpenCode SKIP: Warning message detected"
else
    fail_test "OpenCode SKIP: Warning message missing"
fi
((TESTS_TOTAL++))

# Verify no OpenCode file was created (SKIP behavior)
if [[ ! -f "$TEST_HOME/.config/opencode/opencode.json" ]]; then
    pass_test "OpenCode SKIP: No file created (correctly skipped)"
else
    fail_test "OpenCode SKIP: File was created despite skip"
fi
((TESTS_TOTAL++))

# Check specification pending message
if echo "$OPENCODE_OUTPUT" | grep -q "specification pending"; then
    pass_test "OpenCode SKIP: Specification pending message detected"
else
    fail_test "OpenCode SKIP: Specification pending message missing"
fi

echo ""

# Test 4: Registry Tracking (Codex only due to OpenCode SKIP)
echo "=== Test 4: Registry Tracking ==="
((TESTS_TOTAL++))
if [[ -f "$TEST_HOME/.mcp/state/generated.json" ]]; then
    REGISTRY_CONTENT=$(cat "$TEST_HOME/.mcp/state/generated.json")

    if echo "$REGISTRY_CONTENT" | jq empty 2>/dev/null; then
        pass_test "Registry: Valid JSON format"
    else
        fail_test "Registry: Valid JSON format"
    fi
    ((TESTS_TOTAL++))

    # Since OpenCode is skipped, registry should be empty or minimal
    if echo "$REGISTRY_CONTENT" | jq -e '.files | length == 0' >/dev/null 2>&1; then
        pass_test "Registry: Empty files object (OpenCode skipped)"
    else
        fail_test "Registry: Should be empty due to OpenCode skip"
    fi
    ((TESTS_TOTAL++))
else
    # Registry file might not be created if no JSON files are generated
    pass_test "Registry: File not created (acceptable - no JSON files generated)"
    ((TESTS_TOTAL += 2))
fi

echo ""

# Test 5: Hybrid Generation Detection (TOML only - OpenCode skipped)
echo "=== Test 5: Hybrid Generation Detection ==="
INVENTORY_OUTPUT=$(HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --inventory --check-env off 2>&1)

((TESTS_TOTAL++))
if echo "$INVENTORY_OUTPUT" | grep -q "GENERATED.*config\.toml"; then
    pass_test "Detection: TOML file via comment signature"
else
    fail_test "Detection: TOML file not detected"
fi

((TESTS_TOTAL++))
# OpenCode file should be MISSING due to skip behavior
if echo "$INVENTORY_OUTPUT" | grep -q "MISSING.*opencode\.json"; then
    pass_test "Detection: OpenCode file missing (correctly skipped)"
elif echo "$INVENTORY_OUTPUT" | grep -q "opencode\.json"; then
    fail_test "Detection: OpenCode file should be missing due to skip"
else
    pass_test "Detection: OpenCode file absent from inventory (acceptable)"
fi

echo ""

# Test 6: Error Handling
echo "=== Test 6: Error Handling ==="
# Create invalid JSON configuration
cat > "$TEST_HOME/.mcp/servers-invalid.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    // Invalid JSON comment
    "invalid": true
  }
}
EOF

((TESTS_TOTAL++))
EXIT_CODE=0
HOME="$TEST_HOME" MASTER_FILE="$TEST_HOME/.mcp/servers-invalid.json" /home/nixos/.mcp/mcp-sync --target codex --dry-run --check-env off >/dev/null 2>&1 || EXIT_CODE=$?

if [[ $EXIT_CODE -ne 0 ]]; then
    pass_test "Error handling: Rejects invalid JSON"
else
    fail_test "Error handling: Should reject invalid JSON"
fi

echo ""

# Test 7: Deterministic Behavior
echo "=== Test 7: Deterministic Behavior ==="
# Create configuration with multiple servers
cat > "$TEST_HOME/.mcp/servers-multi.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    "zebra": {
      "type": "stdio",
      "command": "zebra",
      "args": [],
      "env": {},
      "tags": ["codex"]
    },
    "alpha": {
      "type": "stdio",
      "command": "alpha",
      "args": [],
      "env": {},
      "tags": ["codex"]
    }
  },
  "profiles": {
    "full": ["zebra", "alpha"]
  }
}
EOF

# Generate output twice and compare
rm -f "$TEST_HOME/.codex/config.toml"
HOME="$TEST_HOME" MASTER_FILE="$TEST_HOME/.mcp/servers-multi.json" /home/nixos/.mcp/mcp-sync --target codex --apply --check-env off >/dev/null 2>&1
FIRST_OUTPUT=$(cat "$TEST_HOME/.codex/config.toml")

rm -f "$TEST_HOME/.codex/config.toml"
HOME="$TEST_HOME" MASTER_FILE="$TEST_HOME/.mcp/servers-multi.json" /home/nixos/.mcp/mcp-sync --target codex --apply --check-env off >/dev/null 2>&1
SECOND_OUTPUT=$(cat "$TEST_HOME/.codex/config.toml")

((TESTS_TOTAL++))
if [[ "$FIRST_OUTPUT" == "$SECOND_OUTPUT" ]]; then
    pass_test "Deterministic: Identical outputs across runs"
else
    fail_test "Deterministic: Outputs differ between runs"
fi

echo ""

# Test 8: Environment Variable Controls
echo "=== Test 8: Environment Variable Controls ==="
((TESTS_TOTAL++))
EXIT_CODE=0
HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target codex --dry-run --check-env off >/dev/null 2>&1 || EXIT_CODE=$?

if [[ $EXIT_CODE -eq 0 ]]; then
    pass_test "Environment: CHECK_ENV=off bypass works"
else
    fail_test "Environment: CHECK_ENV=off should bypass validation"
fi

echo ""

# Test 9: Absolute Path Validation
echo "=== Test 9: Absolute Path Validation ==="
# Create configuration with relative path in args
cat > "$TEST_HOME/.mcp/servers-relative.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    "relative-path": {
      "type": "stdio",
      "command": "node",
      "args": ["./relative/path/script.js"],
      "env": {},
      "tags": ["codex"]
    }
  },
  "profiles": {
    "test": ["relative-path"]
  }
}
EOF

((TESTS_TOTAL++))
EXIT_CODE=0
RELATIVE_OUTPUT=$(HOME="$TEST_HOME" MASTER_FILE="$TEST_HOME/.mcp/servers-relative.json" /home/nixos/.mcp/mcp-sync --target codex --dry-run --check-env off 2>&1) || EXIT_CODE=$?

if [[ $EXIT_CODE -ne 0 ]] && echo "$RELATIVE_OUTPUT" | grep -q "Relative path detected"; then
    pass_test "Absolute Path: Rejects relative paths correctly"
else
    fail_test "Absolute Path: Should reject relative paths"
fi

echo ""

# Test 10: Claude Output Guard (Git Project Detection)
echo "=== Test 10: Claude Output Guard ==="
# Test outside git project (current temp dir)
((TESTS_TOTAL++))
CLAUDE_OUTPUT=$(HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target claude --dry-run --check-env off 2>&1)

if echo "$CLAUDE_OUTPUT" | grep -q "WARNING: Claude target skipped - not in a git project"; then
    pass_test "Claude Guard: Detects non-git directory correctly"
else
    fail_test "Claude Guard: Should detect non-git directory"
fi

echo ""

# Test 11: Symlink Protection
echo "=== Test 11: Symlink Protection ==="
# Create a symlink target file
touch "$TEST_HOME/real-config.toml"
ln -s "$TEST_HOME/real-config.toml" "$TEST_HOME/.codex/config.toml"

((TESTS_TOTAL++))
SYMLINK_OUTPUT=$(HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target codex --apply --check-env off 2>&1)

if echo "$SYMLINK_OUTPUT" | grep -q "is a symlink (protected from overwrite)"; then
    pass_test "Symlink Protection: Detects and protects symlinks"
else
    fail_test "Symlink Protection: Should protect symlinks"
fi

# Clean up symlink
rm -f "$TEST_HOME/.codex/config.toml" "$TEST_HOME/real-config.toml"

echo ""

# Test 12: Registry Flock Protection (Basic Test)
echo "=== Test 12: Registry Flock Protection ==="
((TESTS_TOTAL++))
# Simple test: ensure registry operations complete without flock errors
FLOCK_OUTPUT=$(HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target codex --apply --check-env off 2>&1)

if ! echo "$FLOCK_OUTPUT" | grep -q "Failed to acquire registry lock"; then
    pass_test "Registry Flock: No lock acquisition failures"
else
    fail_test "Registry Flock: Lock acquisition failed"
fi

echo ""

# Test 13: Diff Fallback Functionality
echo "=== Test 13: Diff Fallback Functionality ==="
# Create existing file and test diff output
cat > "$TEST_HOME/.codex/config.toml" <<'EOF'
# Old configuration
[mcp_servers.old]
command = "old-command"
args = []
EOF

((TESTS_TOTAL++))
DIFF_OUTPUT=$(HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target codex --dry-run --check-env off 2>&1)

# Check that diff output is present (either git diff or system diff)
if echo "$DIFF_OUTPUT" | grep -E "(\-\-\-|\+\+\+|@@|Generated by mcp-sync)"; then
    pass_test "Diff Fallback: Shows configuration differences"
else
    fail_test "Diff Fallback: Should show differences"
fi

echo ""

# Test 14: Registry Absolute Path Normalization
echo "=== Test 14: Registry Absolute Path Normalization ==="
# Create a JSON config with claude target (if we can make a git repo)
mkdir -p "$TEST_HOME/git-project/.git"
cat > "$TEST_HOME/git-project/.mcp/servers.json" <<'EOF'
{
  "version": "1.0",
  "mcpServers": {
    "test": {
      "type": "stdio",
      "command": "test",
      "args": [],
      "env": {},
      "tags": ["claude"]
    }
  },
  "profiles": {
    "test": ["test"]
  }
}
EOF

# Change to git project and run to generate registry
cd "$TEST_HOME/git-project"
((TESTS_TOTAL++))
REGISTRY_OUTPUT=$(HOME="$TEST_HOME" MASTER_FILE="$TEST_HOME/git-project/.mcp/servers.json" /home/nixos/.mcp/mcp-sync --target claude --apply --check-env off 2>&1)

# Check if registry was created and contains absolute paths
if [[ -f "$TEST_HOME/.mcp/state/generated.json" ]]; then
    REGISTRY_CONTENT=$(cat "$TEST_HOME/.mcp/state/generated.json")
    if echo "$REGISTRY_CONTENT" | jq -e '.files | keys[]' 2>/dev/null | grep -q '^/'; then
        pass_test "Registry Normalization: Contains absolute paths"
    else
        fail_test "Registry Normalization: Should contain absolute paths"
    fi
else
    fail_test "Registry Normalization: Registry file not created"
fi

# Return to original directory
cd "$TEST_HOME"

echo ""

# Test 15: CWD Independence Test
echo "=== Test 15: CWD Independence Test ==="
# Test that registry lookup works regardless of current directory
((TESTS_TOTAL++))

# Create a subdirectory and run from there
mkdir -p "$TEST_HOME/subdir"
cd "$TEST_HOME/subdir"

# Run inventory from subdirectory
CWD_OUTPUT=$(HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --inventory --check-env off 2>&1)

# Check that inventory still works (should show previous TOML file)
if echo "$CWD_OUTPUT" | grep -q "config.toml"; then
    pass_test "CWD Independence: Inventory works from any directory"
else
    fail_test "CWD Independence: Inventory should work from any directory"
fi

# Return to test home
cd "$TEST_HOME"

echo ""

# Test 16: Target All Behavior with New Restrictions
echo "=== Test 16: Target All Behavior with New Restrictions ==="
((TESTS_TOTAL++))

# Test --target all outside git project (should exclude Claude and OpenCode)
ALL_OUTPUT=$(HOME="$TEST_HOME" /home/nixos/.mcp/mcp-sync --target all --dry-run --check-env off 2>&1)

if echo "$ALL_OUTPUT" | grep -q "excludes Claude.*not in git project" && echo "$ALL_OUTPUT" | grep -q "excludes.*OpenCode.*specification pending"; then
    pass_test "Target All: Correctly excludes Claude and OpenCode with reasons"
else
    fail_test "Target All: Should exclude Claude and OpenCode with reasons"
fi

echo ""

# Cleanup
rm -rf "$TEST_HOME"

# Summary
echo "🏁 BEHAVIORAL PROTECTION TEST SUMMARY"
echo "===================================="
echo "Total Tests: $TESTS_TOTAL"
echo "Passed: $TESTS_PASSED"
echo "Failed: $TESTS_FAILED"
echo "Success Rate: $(( TESTS_PASSED * 100 / TESTS_TOTAL ))%"

if [[ $TESTS_FAILED -eq 0 ]]; then
    echo ""
    echo "🎉 SUCCESS: All behavioral protection tests passed!"
    echo ""
    echo "🔒 Protected Features:"
    echo "   ✅ DRY RUN mode safety (no file modification)"
    echo "   ✅ Codex TOML rendering with generation signatures"
    echo "   ✅ OpenCode SKIP behavior with proper warnings"
    echo "   ✅ Registry-based tracking for JSON files with flock protection"
    echo "   ✅ Hybrid generation detection (TOML comments + JSON registry)"
    echo "   ✅ Error handling for invalid configurations"
    echo "   ✅ Deterministic sorting and output reproducibility"
    echo "   ✅ Environment variable validation controls"
    echo "   ✅ Absolute path validation and relative path rejection"
    echo "   ✅ Claude output guard (git project boundary detection)"
    echo "   ✅ Symlink protection across all operations"
    echo "   ✅ Registry absolute path normalization"
    echo "   ✅ CWD-independent operation"
    echo "   ✅ Diff fallback functionality"
    echo ""
    echo "🛡️ Safety Measures Verified:"
    echo "   ✅ HOME isolation to temporary directories"
    echo "   ✅ Safe target selection with smart exclusions"
    echo "   ✅ OpenCode specification pending protection"
    echo "   ✅ Claude project boundary enforcement"
    echo "   ✅ Symlink overwrite prevention"
    echo "   ✅ Registry concurrent access protection (flock)"
    echo "   ✅ File pollution prevention"
    echo ""
    echo "🧹 Cleaned up test environment: $TEST_HOME"
    echo ""
    echo "✨ mcp-sync v2.0 Production Perfect behavior is fully protected and verified!"
    exit 0
else
    echo ""
    echo "❌ FAILURE: $TESTS_FAILED test(s) failed!"
    echo ""
    echo "⚠️  Current mcp-sync behavior is NOT fully protected."
    echo "    Please review and fix failing tests before relying on this harness."
    exit 1
fi