api_key: ENC[AES256_GCM,data:8/Lh40NxOALtYOWtSIWTKETg,iv:NiwX8B1qf7rt3JAO3LBFKZo8C1YrYDV4vOzb4bf6OXc=,tag:Wdl7XbyiOaR9C7nZlgrP+g==,type:str]
db_password: ENC[AES256_GCM,data:LuHbe/Is+G1oohU7fOWjIdVCrHXV4QVb,iv:KGapU6zoLUWR68AwfzQl5hY97bepnKCWcKFCP1BWT4Q=,tag:TMNdKuBb63XLJ5204ksYkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xe09p4793xh9rptl3m7tdhxey5anc7erx8gau440ktt3qsknmq9q3nc3me
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUldSVXVxcWR1Tk9CR0o5
            Z1NQd1NlU0JPZEs5Q291bVlzQ0htdVRiZlJNCjBpVkRpV2dPeHFTWTA2eWwwUVJw
            TEVKV1NxUEdDMG9vRnc4ekkzYkpGSjAKLS0tIHYwQ1A4MlpXNlBycUNrV21YOHgy
            YkxEL2xLRTFiVzdtSGZWdjcyMVRJRHcK7sodkdyuoGDHin6zFSdHWM9FgaJAWh/f
            UMqzD6F3rbwhYm6XJdjPUO387hTLbN+DKsW0Qrd868b0D3u6nVkS8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T10:10:06Z"
    mac: ENC[AES256_GCM,data:7wzdhR3ex7rct5Q5Czk1jZHV3r3NWx1D+fkQ/5t3beApwA/tu49GRvmSe5EXfXS696mbQVkyguFlsMzF85G6sopZi53LmAYX9OCRZQFfSqu7EU67nJAC4YWUdcrX7898DmTTh8vgtEb9OKdKlWlLBQoWOd+WrNnUT1zWr3PrESw=,iv:uwcI5nX/Jo47wiOxG+SQfTCbZ4zSvaX7ro8aI1jwLCs=,tag:0IMiAsNsjWFtymo3k983IQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
