# sops-flake template configuration
# Replace REPLACE_ME with your age public key:
# age-keygen -y ~/.config/sops/age/keys.txt

creation_rules:
  # Application secrets
  - path_regex: secrets/.*\.(yaml|json)$
    key_groups:
      - age:
          - REPLACE_ME
  
  # Environment files (optional)
  - path_regex: .*\.env\.enc$
    key_groups:
      - age:
          - REPLACE_ME

# Configuration options
stores:
  yaml:
    indent: 2
  json:
    indent: 2